// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a listed result came from, so the UI can be honest about it.
 */
export type CacheSource = { "kind": "fresh" } | { "kind": "cached" };
