// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The audio codec radio-browser reports, normalised from its free-text `codec` field.
 * `raw` on [`Station`] keeps the original string.
 */
export type Codec = "mp3" | "aac" | "aac_plus" | "ogg" | "flac" | "unknown";
