// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A country row from `/json/countries`, after [`crate::normalise::countries`].
 */
export type Country = { 
/**
 * ISO 3166-1 alpha-2, upper case — the key `list_stations` takes.
 */
code: string, name: string, 
/**
 * radio-browser's own count for the code (with `hidebroken=true`, the checked-OK count).
 * The app lists its own filtered, capped count once a list is cached; this one fills the
 * dropdown before that.
 */
station_count: number, };
