// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefreshOutcome } from "./RefreshOutcome";

/**
 * Payload of `countries:updated`.
 */
export type CountriesUpdated = { outcome: RefreshOutcome, };
