// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A dot on the pane (M4c): its centre and radius, points; its stations (uuids, list order) and
 * their majority place.
 */
export type Dot = { x: number, y: number, r: number, n: number, uuids: Array<string>, place: string, };
