// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One equalizer band as shown in the UI.
 */
export type EqBand = { index: number, center_hz: number, gain_db: number, };
