// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Machine-readable reason for a playback failure.
 */
export type ErrorCode = "network" | "http" | "unsupported_format" | "decode" | "device" | "invalid_url";
