// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dot } from "./Dot";
import type { FrameStats } from "./FrameStats";
import type { Inset } from "./Inset";
import type { Shape } from "./Shape";
import type { View } from "./View";

export type Frame = { view: View, level: number, neighbours: Array<Shape>, land: Array<Shape>, subdivisions: Array<Array<[number, number]>>, 
/**
 * At the fit view only (D7).
 */
insets: Array<Inset>, 
/**
 * The located dots on the pane, larger first (`Store::frame_dots`); empty from `frame`.
 */
dots: Array<Dot>, stats: FrameStats, };
