// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FrameStats = { vertices: number, rings_considered: number, rings_skipped: number, 
/**
 * Blobs the frame needed and the resource does not store, counted per unit (review finding
 * 9): a unit the index admitted at the view's level, once per inset for a unit holding its
 * parts, and the country's subdivisions when one of its lines meets the view. 0 at the
 * golden pane (the coverage test).
 */
missing_blobs: number, 
/**
 * Insets not drawn at the fit view: the band's stored scale is 0 (I1: the box cannot meet
 * the minimum there — Hawaii below 274, Svalbard at 225–257), or the box, anchored at this
 * pane, leaves the pane, meets the controls' rect or overlaps a box drawn before it in table
 * order (review 2, finding 4; review 3, finding 2). 0 at every band but those the tool's
 * tables name.
 */
insets_dropped: number, };
