// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * In-band ICY metadata (`StreamTitle`), emitted every time it changes.
 */
export type IcyMetadata = { title: string | null, };
