// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shape } from "./Shape";

export type Inset = { label: string, 
/**
 * x, y, w, h, points.
 */
rect: [number, number, number, number], land: Array<Shape>, };
