// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheSource } from "./CacheSource";
import type { Station } from "./Station";

/**
 * One country's station list with its provenance.
 */
export type ListedStations = { country_code: string, items: Array<Station>, fetched_at: bigint, age_secs: bigint, source: CacheSource, refreshing: boolean, };
