// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheSource } from "./CacheSource";
import type { Country } from "./Country";

/**
 * The countries list with its provenance.
 */
export type ListedCountries = { items: Array<Country>, 
/**
 * Unix seconds when the network answered.
 */
fetched_at: bigint, age_secs: bigint, source: CacheSource, 
/**
 * A background refresh is in flight for this list (stale-while-revalidate); a
 * `stations:updated` event follows when it lands.
 */
refreshing: boolean, };
