// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The map band's rect in the panel, points, top-left origin (M4b commit 6). Crosses the boundary
 * inside [`PanelLayout`] as `band`, `None` when the layout has no band — the collapsed height, or
 * an expanded height whose band would be under `BAND_FLOOR`.
 */
export type MapBand = { x: number, y: number, width: number, height: number, };
