// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `map_hit` answers: the dot's stations (uuids, list order), their count and the dot's
 * place (empty when none of its stations has one).
 */
export type MapHit = { uuids: Array<string>, n: number, place: string, };
