// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the page accumulated since its last pull: wheel and drag deltas in points (a CSS px is a
 * point), zoom steps from the `−`/`+` controls (negative = out), and whether `fit` was pressed.
 */
export type MapInputs = { pan_pt: [number, number], zoom_steps: number, fit: boolean, };
