// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Frame } from "./Frame";
import type { MapBand } from "./MapBand";
import type { MapStatus } from "./MapStatus";
import type { View } from "./View";

export type MapReply = { 
/**
 * Grows with every frame produced and every selection; the page draws a reply only if this
 * is newer than the frame on screen.
 */
seq: number, status: MapStatus, band: MapBand | null, 
/**
 * With `Frame`: the clamped view the frame was made at, and the frame.
 */
view: View | null, frame: Frame | null, };
