// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a pull answers (the frame as JSON — Step 0's measured path; replies, not events).
 */
export type MapStatus = "frame" | "no_map" | "unavailable" | "no_band";
