// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PanelHeight } from "./PanelHeight";
import type { PanelView } from "./PanelView";

/**
 * What the page renders: the pane, the height state, the size in points, and whether expansion
 * is available on the display the icon is on (decision D1's floor; decision D4 shows the control
 * disabled when it is not). Emitted as `panel:layout` on every effective show and every resize,
 * and answered by `get_panel_layout` on mount. **The page is told the height; it never computes
 * it** (D1's consequence; CLAUDE.md, "The one rule"). Supersedes M2c's `panel:view` event and
 * `get_panel_view`, whose value is the `view` field.
 */
export type PanelLayout = { view: PanelView, state: PanelHeight, width: number, height: number, expandable: boolean, };
