// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a [`PanelLayout`] reaches the page — see its `transition` field.
 */
export type PanelTransition = "show" | "resize";
