// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PanelHeight } from "./PanelHeight";
import type { PanelTransition } from "./PanelTransition";
import type { PanelView } from "./PanelView";

/**
 * What the page renders: the pane, the height state, the size in points, and whether expansion
 * is available on the display the icon is on (decision D1's floor; decision D4 shows the control
 * disabled when it is not). Emitted as `panel:layout` on every effective show and every resize,
 * and answered by `get_panel_layout` on mount. **The page is told the height; it never computes
 * it** (D1's consequence; CLAUDE.md, "The one rule"). Supersedes M2c's `panel:view` event and
 * `get_panel_view`, whose value is the `view` field.
 */
export type PanelLayout = { 
/**
 * Whether this layout arrives on a show — the hidden panel's frame is **already** at
 * `width`×`height` when the page receives it — or on a resize of the visible panel, whose
 * frame changes only after the page commits. The page needs the difference: a hidden
 * WKWebView fires no `resize`, so on a show it takes `height` as the window's height rather
 * than its last `resize` reading (`/code-review` C2, 2026-09-18: a show shorter than the
 * last visible height committed with the expanded pane in a collapsed popover's first frame).
 */
transition: PanelTransition, 
/**
 * Increments on every layout request. The page echoes it in `panel_layout_committed`, so a
 * report for a layout that has since been superseded, completed or cancelled is a logged
 * no-op rather than a second apply (decision D3). `u32`, not `u64`: ts-rs maps `u64` to
 * `bigint`, and a click counter does not need it.
 */
generation: number, view: PanelView, state: PanelHeight, width: number, height: number, expandable: boolean, };
