// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which pane the popover shows. Crosses the boundary twice — as the `panel:view` event on
 * every effective show and as the `get_panel_view` command's answer — so it is a generated
 * type, not a string agreed on by hand on both sides (`/code-review` finding 7, 2026-09-17).
 */
export type PanelView = "transport" | "about";
