// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which pane the popover shows. Crosses the boundary as the `view` field of [`PanelLayout`] —
 * the `panel:layout` event and the `get_panel_layout` answer (M2c's `panel:view` and
 * `get_panel_view` until M2d) — so it is a generated type, not a string agreed on by hand on both
 * sides (`/code-review` finding 7, 2026-09-17).
 */
export type PanelView = "transport" | "about";
