// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the two heights the popover is at, or is asked for. Crosses the boundary inside
 * [`PanelLayout`], so it is a generated type, not a string agreed on by hand on both sides.
 */
export type PanelHeight = "collapsed" | "expanded";
