// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * The single source of truth for what the UI shows in the transport area.
 */
export type PlaybackState = { "kind": "idle" } | { "kind": "connecting" } | { "kind": "buffering" } | { "kind": "playing" } | { "kind": "paused" } | { "kind": "reconnecting", attempt: number, } | { "kind": "error", code: ErrorCode, message: string, };
