// Placeholder — regenerated by `cargo test` (ts-rs). Do not edit by hand.
import type { ErrorCode } from "./ErrorCode";

export type PlaybackState =
  | { kind: "idle" }
  | { kind: "connecting" }
  | { kind: "buffering" }
  | { kind: "playing" }
  | { kind: "paused" }
  | { kind: "reconnecting"; attempt: number }
  | { kind: "error"; code: ErrorCode; message: string };
