// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `stream-download`'s internal reconnect count (its own idle-`retry_timeout` recovery, not
 * one of our external `Backoff` attempts — see `stream::open`'s `Settings::on_reconnect`).
 * Cumulative for the current session (since the last `Play`); emitted whenever it advances.
 */
export type ReconnectInfo = { count: bigint, };
