// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a background refresh ended — carried by `stations:updated` / `countries:updated`, so
 * the page can tell "re-request, the list changed" from "the expired list stays; stop saying
 * refreshing". Added 2026-09-22 (M3a acceptance item 6): before it, a failed refresh emitted
 * nothing and the page's `refreshing…` never cleared.
 */
export type RefreshOutcome = "landed" | "failed";
