// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rings in pane points (exterior first, then holes; fill rule even-odd).
 */
export type Shape = { rings: Array<Array<[number, number]>>, };
