// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload of `stations:updated`.
 */
export type StationsUpdated = { country_code: string, };
