// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Codec } from "./Codec";

/**
 * A station as the UI needs it, after [`crate::normalise::stations`].
 */
export type Station = { uuid: string, 
/**
 * Trimmed.
 */
name: string, 
/**
 * `url_resolved` — the playable URL, redirects already followed by radio-browser's checker.
 */
url: string, homepage: string, favicon: string, country_code: string, codec: Codec, 
/**
 * The `codec` string as served (`MP3`, `AAC+`, `AAC,H.264`, `UNKNOWN`, `` …).
 */
codec_raw: string, 
/**
 * `None` when radio-browser reports 0 — unknown, not broken (decided 2026-09-21).
 */
bitrate_kbps: number | null, 
/**
 * radio-browser's `hls == 1` (kept and flagged; playback is M3c's).
 */
hls: boolean, 
/**
 * The codec string names a video codec (`AAC,H.264`, 41 of 25 236 in the census): a TV
 * feed listed as radio. Kept and flagged; whether to hide it is M3c's decision.
 */
video: boolean, votes: bigint, click_count: bigint, click_trend: bigint, 
/**
 * `(lat, lng)`; `None` when either is null **or both are 0** (a known default, not a
 * position — none seen in the census, the rule is a guard).
 */
geo: [number, number] | null, 
/**
 * `lastcheckok == 1`. With `hidebroken=true` on the request this is always true; kept so a
 * list from any other source can be filtered the same way.
 */
last_check_ok: boolean, };
