// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Facts about the open stream, emitted once the decoder has probed it.
 */
export type StreamInfo = { 
/**
 * Container/codec description from the HTTP `Content-Type` (e.g. `audio/mpeg`, `audio/aac`).
 */
content_type: string | null, 
/**
 * From the `icy-br` header, if the server sends it.
 */
bitrate_kbps: number | null, 
/**
 * From the `icy-name` header, if the server sends it.
 */
station_name: string | null, sample_rate: number, channels: number, };
