// Placeholder — regenerated by `cargo test` (ts-rs). Do not edit by hand.
export type StreamInfo = {
  content_type: string | null;
  bitrate_kbps: number | null;
  station_name: string | null;
  sample_rate: number;
  channels: number;
};
