// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A view: its centre in the country's frame LAEA, km, and its scale, km/pt.
 */
export type View = { centre: [number, number], scale: number, };
